### ISSUE TITLE
Reporters broken in 2.5.1 release

### ISSUE THREAD

**Issue by csMACnz** [xunit/visualstudio.xunit#384]
I'm still investigating the actual root cause or workarounds.

The symptom I am having is that the teamcity reporter is no longer working in `xunit.runner.visualstudio` 2.5.1. This was working in `xunit.runner.visualstudio` 2.5.0.

I do get this error message when using `-- xUnit.ReporterSwitch=teamcity`

```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.1.1+5fe7eebc65 (64-bit .NET 7.0.11)
[xUnit.net 00:00:00.02] Could not find requested reporter 'teamcity'
```

I've narrowed down the difference to the fact that the dlls are no longer included in the build folder of the nuget package. Though still investigating if that is the true cause or not.

![image](https://github.com/xunit/visualstudio.xunit/assets/1768046/a811eabc-a534-4978-ae16-3713010c6b43)

Which is these commits: https://github.com/xunit/visualstudio.xunit/commit/0d583f282abe40548466205e7328cc9e39cd3d94 https://github.com/xunit/visualstudio.xunit/commit/96555ae16f077124a853ffad1a643d990a331ce8

Installing `xunit.runner.reporters` into the project has not fixed the issue but testing continues.

Runtime: .Net 7.0

**Comment by csMACnz** [comment]
After some Investigation, the best I can tell is that `xunit.runner.visualstudio` (`xunit.runner.visualstudio.dotnetcore.testadapter.dll`) which lives in the build folder is using that build folder for the reflection and so when `xunit.runner.reporters.netcoreapp10.dll` is not present in that folder the reporters from inside it are not discovered.

I haven't looked and checked out the discovery code to see if or how it could look inside the test project bin folder for those missing dlls or not... (or if this is the true issue)

**Comment by bradwilson** [comment]
@csMACnz This probably came from #383.

**Comment by bradwilson** [comment]
Fixed in `2.5.2-pre.3`

**Comment by csMACnz** [comment]
I can confirm that the changes in `2.5.2-pre.3` have fixed this issue 🎉 

Thanks for the prompt resolution, looking forward to 2.5.2 to drop 🙇‍♂️

**Comment by bradwilson** [comment]
I'll wait a few days to see if any other issues surface, and then just cut it over.

Thanks!

**Comment by nvborisenko** [comment]
It affected 3rd-party reporter https://github.com/reportportal/agent-net-xunit/issues/27. It worked good with `2.5.0`.

File name of that reporter is `ReportPortal.XUnit.reporters.dll` which is located in output `bin` folder. Tests target `net7.0`.

I also tried `2.5.2-pre.3`, still doesn't work.

**Comment by bradwilson** [comment]
@nvborisenko Please open a new issue with a repro project. Thanks!
